### ISSUE TITLE
[BUG] Hot-reloading fails for first tool when ./tools directory is empty at Agent initialization

### ISSUE THREAD

**Issue by cagataycali** [strands-agents/sdk-python#264]
### Checks

- [x] I have updated to the lastest minor and patch version of Strands
- [x] I have checked the documentation and this is not expected behavior
- [x] I have searched [./issues](./issues?q=) and there are no duplicates of my issue

### Strands Version

0.1.18

### Python Version

3.13.3

### Operating System

macOS (Darwin with Clang 17.0.0)

### Installation Method

git clone

### Steps to Reproduce

Hot-reloading of tools from the `./tools` directory fails when the directory is empty during Agent initialization. The first tool added to an empty `./tools` directory is not automatically loaded, breaking the expected hot-reload functionality.

1. **Setup the environment:**
   ```bash
   git clone git@github.com:strands-agents/sdk-python.git /tmp/sdk-python && cd /tmp/sdk-python
   python3 -m venv .venv && source .venv/bin/activate && pip3 install -e ".[dev]"
   ```

2. **Ensure ./tools directory exists but is empty:**
   ```bash
   mkdir -p tools
   # Ensure tools directory is empty
   rm -f tools/*.py
   ```

3. **Create a simple agent in Python REPL:**
   ```python
   from strands import Agent
   agent = Agent()
   print(agent.tool_config)  # Shows: {'tools': [], 'toolChoice': {'auto': {}}}
   ```

4. **Add a tool to ./tools directory while REPL is running:**
   ```python
   # Create tools/basic_calculator.py with @tool decorator
   # (see full tool code in Additional Context section)
   ```

5. **Check if tool is loaded:**
   ```python
   print(agent.tool_config)  # Still shows: {'tools': [], 'toolChoice': {'auto': {}}}
   print(agent.tool_names)   # Shows: []
   ```

### Expected Behavior

When a tool is added to the `./tools` directory, it should be automatically hot-reloaded and available in:
- `agent.tool_config` - should include the new tool specification
- `agent.tool_names` - should include the tool name in the list
- `agent.tool.tool_name()` - should be callable

This should work regardless of whether the `./tools` directory was empty when the Agent was initialized.

### Actual Behavior

- **First tool addition**: Tool is NOT automatically loaded when added to an initially empty `./tools` directory
- **Subsequent tool additions**: Once at least one tool exists, additional tools ARE automatically hot-reloaded
- **Workaround**: Restarting the Python process loads the tool correctly

## Code Analysis

Based on examination of the codebase, the issue appears to be in the `ToolWatcher` initialization logic:

1. **In `Agent.__init__()`**: The `ToolWatcher` is only initialized if `load_tools_from_directory=True`
2. **In `ToolRegistry.initialize_tools()`**: Tool discovery happens, but if no tools exist, the watcher may not be properly set up
3. **In `ToolWatcher.start()`**: The file system watcher is configured, but may not monitor empty directories effectively

## Test Case Evidence

```python
# Case 1: Empty tools directory - FAILS
agent = Agent()
# Add tool to empty ./tools/
# Result: tool_config remains empty

# Case 2: Pre-existing tool - WORKS  
agent = Agent()  # with existing tool in ./tools/
# Add another tool
# Result: new tool appears in tool_config

# Case 3: Restart after adding to empty directory - WORKS
# Exit Python, add tool, restart Python
agent = Agent()
# Result: tool_config includes the tool
```

## Proposed Solution Areas

The issue likely resides in one or more of these areas:

1. **`ToolWatcher` initialization**: May need to properly handle empty directories
2. **File system monitoring**: The watchdog observer might not be monitoring empty directories
3. **Tool discovery timing**: Initial discovery vs. runtime discovery synchronization

## Additional Context

**Sample tool used for testing:**
```python
# tools/basic_calculator.py
from strands import tool

@tool
def basic_calculator(expression: str) -> dict:
    """
    A very simple calculator for basic arithmetic only.
    
    Supports: +, -, *, /, and parentheses
    
    Args:
        expression: Simple math expression (e.g., "2 + 3", "10 / 2", "(5 + 3) * 2")
        
    Returns:
        Dictionary with the calculation result
    """
    try:
        # Only allow basic math characters and numbers
        allowed = set('0123456789+-*/().')
        if not all(c in allowed or c.isspace() for c in expression):
            raise ValueError("Only basic math operations allowed: +, -, *, /, ()")
        
        result = eval(expression)
        
        return {
            "status": "success",
            "content": [{"text": f"{expression} = {result}"}]
        }
        
    except ZeroDivisionError:
        return {
            "status": "error",
            "content": [{"text": "Cannot divide by zero"}]
        }
    except:
        return {
            "status": "error",
            "content": [{"text": "Invalid math expression"}]
        }
```

## Impact

This bug affects the developer experience for:
- New users setting up their first Strands agent
- Development workflows where tools are added incrementally
- Any scenario where the `./tools` directory starts empty

## Related Files

- `src/strands/agent/agent.py` - Agent initialization
- `src/strands/tools/registry.py` - Tool discovery and registration
- `src/strands/tools/watcher.py` - File system monitoring for hot-reload

## Verification

This issue can be consistently reproduced with the steps above. The hot-reload functionality works correctly in all cases except when the initial `./tools` directory is empty during Agent initialization.

**Comment by dashapetr** [comment]
Is this a bug? I see that the automatic tool loading and reloading from the ./tools/ directory is addressed in the README.md:

https://github.com/strands-agents/sdk-python/blob/e7d95d6ad2c13dbde6257afbba96802822f70b26/README.md?plain=1#L94

```
from strands import Agent

# Agent will watch ./tools/ directory for changes
agent = Agent(load_tools_from_directory=True)
response = agent("Use any tools you find in the tools directory")
```

**Comment by JackYPCOnline** [comment]
/strands is this issue fixed? can I close this ticket.

**Comment by maxmilian** [comment]
I'd like to pick this up.

Confirmed it still reproduces on current `main`: `strands-py/src/strands/tools/watcher.py` implements only `on_modified` on both `ToolChangeHandler` and the `MasterChangeHandler` that's actually scheduled with the `Observer`. watchdog emits `on_created` (not `on_modified`) for a file that didn't previously exist — e.g. the first tool dropped into an empty `./tools` directory — so that event is dropped at the master handler and the tool never loads until it's later edited.

Planned fix (small, mirrors the earlier closed attempt in #1506): add `on_created` handlers that route through the same reload path as `on_modified`. `reload_tool` already treats a new file like a changed one and is safe to call again when the follow-up `on_modified` fires (hot-reload registration is idempotent), so no double-register issue. I'll add unit tests covering the created-event path alongside the existing `on_modified` ones.

Will open a PR shortly.
